-- -- NOTA: CREACION DE MENUS DE TRANSPORTE:
-- -- =====================================
-- select*from dbo.menu


-- -- go
-- -- create table dbo.menuTransportes(
-- --     id_menu varchar(6),
-- --     descripcion varchar(100),
-- --     data_router varchar(50)
-- -- )


-- delete dbo.menuTransportes
-- -- NOTA: PRIMER NIVEL
-- insert into dbo.menuTransportes
-- select '010000', 'Grupo Bien Policial/Seguridad', null union all
-- select '020000', 'Carga Masiva', null union all
-- select '030000', 'Administrar Vehiculo', null union all
-- select '040000', 'Administrar SOAT', null union all
-- select '050000', 'Administrar SCTR', null union all
-- select '060000', 'Administrar Baja Vehiculo Policial/Seguridad', null union all
-- select '070000', 'Accidentes de Transito', null union all
-- select '080000', 'Papeletas de Infraccion', null union all
-- select '090000', 'Exportacion de Datos', null union all
-- select '100000', 'Mantenimientos', null

-- -- NOTA: SEGUNDO NIVEL
-- insert into dbo.menuTransportes
-- select '010100', 'Registrar/Actualizar Grupo Bien', 'RegistroGrupoBien01' union all
-- select '020100', 'Carga Masiva Policiales', 'CargaMasivaPolicial02' union all
-- select '020200', 'Carga Masiva Seguridad', 'CargaMasivaSeguridad02' union all
-- select '020300', 'Carga Masiva Actualiza datos Vehiculos', null union all
-- select '030100', 'Vehiculo Policial', null union all
-- select '030200', 'Vehiculo Seguridad', null union all
-- select '040100', 'Carga Masiva SOAT', null union all
-- select '040200', 'Registrar/Actualizar SOAT', null union all
-- select '040300', 'Registrar/Actualizar Identificacion Vehicular', null union all
-- select '050100', 'Carga masiva SCTR', null union all
-- select '050200', 'Registrar/Actualizar SCTR', null union all
-- select '060100', 'Carga Masiva Baja Vehiculo', null union all
-- select '060200', 'Registrar/Actualiza Baja Vehiculo', null union all
-- select '070100', 'Carga Masiva Accidentes de Transito', null union all
-- select '070200', 'Registrar/Actualizar Accidentes de Transito', null union all
-- select '080100', 'Registrar/Actualizar Papeletas de Infraccion', null union all
-- select '080200', 'Notificar Papeletas de Infraccion', null union all
-- select '090100', 'Exportar Parque Automotor Policial/Seguridad', null union all
-- select '090200', 'Exportar Certificados SOAT', null union all
-- select '090300', 'Exportar SCTR', null union all
-- select '090400', 'Exportar Accidentes de Transito', null union all
-- select '100100', 'Grupo Bien', null union all
-- select '100200', 'Cantidad Vehiculo', null union all
-- select '100300', 'Alta Vehiculo', null union all
-- select '100400', 'Vehiculo', null union all
-- select '100500', 'Vehiculo Unidad', null union all
-- select '100600', 'Vehiculo Comando', null union all
-- select '100700', 'Operatividad Vehiculo', null union all
-- select '100800', 'Funcion Vehiculo', null union all
-- select '100900', 'Baja Vehiculo', null union all
-- select '101000', 'Certificado SOAT', null union all
-- select '101100', 'SCTR Vehiculo', null union all
-- select '101200', 'Accidentes de Transito', null

-- -- NOTA: TERCER NIVEL
-- insert into dbo.menuTransportes
-- select '030101', 'Vehiculo Nuevo', 'CrudVehiculoPolicial03' union all
-- select '030102', 'Vehiculo Existente', null union all
-- select '030201', 'Vehiculo Nuevo', 'CrudVehiculoSeguridad03' union all
-- select '030202', 'Vehiculo Existente', null union all
-- select '100101', 'Tipo Registro', null union all
-- select '100102', 'Tipo Estado Registro', null union all
-- select '100103', 'Tipo Donante', null union all
-- select '100104', 'Tipo Rubro', null union all
-- select '100105', 'Tipo Procedencia', null union all
-- select '100106', 'Tipo Entidad', null union all
-- select '100107', 'Tipo Documento', null union all
-- select '100108', 'Catalogo Bien', null union all
-- select '100201', 'Tipo Vehiculo', null union all
-- select '100202', 'Tipo Clase Vehiculo', null union all
-- select '100203', 'Tipo Clasificacion Bien', null union all
-- select '100301', 'Tipo Documento', null union all
-- select '100401', 'Tipo Vehiculo', null union all
-- select '100402', 'Tipo Categoria', null union all
-- select '100403', 'Tipo Carroceria', null union all
-- select '100404', 'Tipo Transmision', null union all
-- select '100405', 'Tipo Combustible', null union all
-- select '100406', 'Tipo Zona Registral', null union all
-- select '100407', 'Tipo Situacion Especial', null union all
-- select '100408', 'Tipo Propietario', null union all
-- select '100409', 'Tipo Marca', null union all
-- select '100410', 'Tipo Modelo', null union all
-- select '100411', 'Tipo Color', null union all
-- select '100412', 'Tipo Octanaje', null union all
-- select '100413', 'Tipo Formula Rodante', null union all
-- select '100414', 'Tipo Funcion', null union all
-- select '100415', 'Tipo Modalidad Ingreso', null union all
-- select '100416', 'Tipo Obs. Adquisicion', null union all
-- select '100501', 'Tipo Movimiento', null union all
-- select '100502', 'Tipo Documento', null union all
-- select '100503', 'Tipo Ubicacion', null union all
-- select '100504', 'Tipo Clase Unidad', null union all
-- select '100505', 'Tipo Unidad', null union all
-- select '100601', 'Tipo Movimiento', null union all
-- select '100602', 'Tipo Situacion Policial', null union all
-- select '100603', 'Tipo Documento', null union all
-- select '100701', 'Tipo Estado Vehiculo', null union all
-- select '100702', 'Tipo Estado Operatividad', null union all
-- select '100703', 'Tipo Estado OP Odometro', null union all
-- select '100704', 'Tipo Maestranza', null union all
-- select '100801', 'Tipo Funcion', null union all
-- select '100802', 'Tipo Documento', null union all
-- select '100901', 'Tipo Motivo Baja Vehiculo', null union all
-- select '100902', 'Tipo Lugar de Internamiento', null union all
-- select '101001', 'Tipo Situacion Certificado', null union all
-- select '101002', 'Compañia Seguro', null union all
-- select '101003', 'Tipo Documento', null union all
-- select '101101', 'Compañia de Seguro', null union all
-- select '101102', 'Tipo Siniestro', null union all
-- select '101103', 'Tipo Documento', null union all
-- select '101104', 'Tipo Situacion SCTR', null union all
-- select '101105', 'Monto IGV', null union all
-- select '101201', 'Tipo Siniestro', null union all
-- select '101202', 'Tipo Situacion Accidente', null union all
-- select '101203', 'Tipo Expediente', null union all
-- select '101204', 'Tipo Proceso Judicial', null union all
-- select '101205', 'Tipo Estado Operatividad', null


-- select*from dbo.menuTransportes
